---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "FEMEDIA - Analysis of female represenation in US written online media"
keywords:    "ADA, Quotebank, flatpad, quotes, gender"
description: "A single-page template for Jekyll based blogs (like what you'd use on github pages!)"
source_link: "https://github.com/puentene/nasaflatpad_datastory"
favicon:     #put a path like: "img/logo_1.svg"
touch_icon:  #put a path like: "img/logo_1.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     	'#111111'
  white:     	'#f8f8f8'
  lavender:	'#b0aac0'
  lblue: 	'#c2d4dd'
  lgreen:	'#ddeedd'
  turquoise:	'#5b9aa0'
  purple:  	'#622569'


kramdown:
  auto_ids:  false

